[versions]
androidMinSdk = "21"
androidTargetSdk = "34"
androidCompileSdk = "34"
versionCode = "106"
versionName = "2.5.2"

androidx-datastorePreferencesAndroid = "1.1.0-alpha07"
androidx-material = "1.6.0-beta03"
appUpdateKtx = "2.1.0"
appUpdate = "2.1.0"
avifCoder = "1.5.8"
compose = "2.1.0"
fadingEdges = "1.0.3"
firebaseCrashlyticsKtx = "18.6.0"
konfettiCompose = "2.0.4"
reimagined = "1.5.0"
shadowsPlus = "1.0.4"
exifinterface = "1.3.7"
firebaseAnalyticsKtx = "21.5.0"
firebaseCrashlyticsGradle = "2.9.9"
google-segmentationSelfie = "16.0.0-beta4"
hiltCompiler = "1.1.0"
jvmTarget = "17"

compose-compiler = "1.5.3"
kotlin = "1.9.10"
agp = "8.2.0"
hilt = "2.50"
gms = "4.4.0"

coil = "2.5.0"
coroutines = "1.7.3"
androidx = "1.6.1"
androidxCore = "1.12.0"
androidxLifecycle = "2.6.2"
desugaring = "2.0.4"
firebaseBom = "32.2.2"
firebaseMessaging = "23.4.0"
firebaseGms = "18.2.0"
composeBom = "2023.10.01"
decompose = "2.2.2"
activityCompose = "1.8.2"
kotlinxCollectionsImmutable = "0.3.7"
scrollbar = "1.8.0"
material3 = "1.2.0-beta01"
material3WindowSizeClass = "beta01"
materialIconsExtended = "1.6.0-beta03"
reorderable = "0.9.6"
reviewKtx = "2.0.1"
splashScreen = "1.0.1"
room = "2.6.1"
hiltJetpack = "1.0.0"
yandexMetrica = "5.3.0"
yandexMetricaPush = "2.2.0"
retrofit = "2.9.0"
okHttp = "4.12.0"
chucker = "4.0.0"
gson = "2.10.1"
leakCanary = "2.7"
junit = "4.13.2"
runner = "1.5.2"
espresso = "3.5.1"
mockito = "4.8.0"
testArchCore = "2.1.0"
testCoroutines = "1.5.1"
kotlinxSerializationJson = "1.6.1"
ksp = "1.9.21-1.0.15"
tinkoffSdk = "3.0.0"
androidx-test-ext-junit = "1.1.5"
material = "1.11.0"
documentfile = "1.0.1"
vkauth = "1.2.0"
datastorePreferencesAndroid = "1.0.0"

[libraries]
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialIconsExtended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
avif-coder = { module = "com.github.awxkee:avif-coder", version.ref = "avifCoder" }
compose = { module = "com.github.zed-alpha.shadow-gadgets:compose", version.ref = "compose" }
datastore-preferences-android = { module = "androidx.datastore:datastore-preferences-android", version.ref = "androidx-datastorePreferencesAndroid" }
fadingEdges = { module = "com.github.GIGAMOLE:ComposeFadingEdges", version.ref = "fadingEdges" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
konfetti-compose = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfettiCompose" }
reimagined = { module = "dev.olshevski.navigation:reimagined", version.ref = "reimagined" }
reimagined-hilt = { module = "dev.olshevski.navigation:reimagined-hilt", version.ref = "reimagined" }
shadowsPlus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "shadowsPlus" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coilGif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coilSvg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
androidBuildTools = { module = "com.android.tools.build:gradle", version.ref = "agp" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
jxl-coder-coil = { module = "com.github.awxkee:jxl-coder-coil", version.ref = "avifCoder" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hiltGradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
gmsGradlePlugin = { module = "com.google.gms:google-services", version.ref = "gms" }
kotlinSerializationGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kspGradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
scrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "scrollbar" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
mlkit-segmentation-selfie = { module = "com.google.mlkit:segmentation-selfie", version.ref = "google-segmentationSelfie" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decomposeExtensions = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
viewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger = { module = "com.google.dagger:dagger", version.ref = "hilt" }
room = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
gsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
gms = { module = "com.google.android.gms:play-services-base", version.ref = "firebaseGms" }
push = { module = "com.yandex.android:mobmetricapushlib", version.ref = "yandexMetricaPush" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockitoKotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito" }
testArchCore = { module = "android.arch.core:core-testing", version.ref = "testArchCore" }
testCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "testCoroutines" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
yandexMetrica = { module = "com.yandex.android:mobmetricalib", version.ref = "yandexMetrica" }
chuckerDebug = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chuckerRelease = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
kotlin-reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
vkauth = { module = "com.petersamokhin.vksdk.android:auth", version.ref = "vkauth" }
androidx-datastore-preferences-android = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferencesAndroid" }