name: Bug Report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what should have happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: You can drag and drop images here...

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: e.g., Samsung Galaxy S23
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g., Android 14
    validations:
      required: true

  - type: input
    id: locale
    attributes:
      label: Locale
      placeholder: e.g., en-US, ru-RU

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: dropdown
    id: variant
    attributes:
      label: FOSS or Market
      description: Which variant of the app are you using?
      options:
        - FOSS
        - Market (Google Play/App Store)
    validations:
      required: true
